FROM golang:1.24-alpine AS builder
WORKDIR /src

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o /server_main ./server_main

FROM alpine:latest
RUN apk --no-cache add ca-certificates
WORKDIR /app
COPY --from=builder /server_main ./
COPY start.sh .
COPY wait-for.sh .
RUN chmod +x /app/start.sh /app/wait-for.sh
COPY db/migration ./db/migration

CMD ["./server_main"]
ENTRYPOINT ["/app/start.sh"]