name: Deploy to staging

on:
  push:
    branches: [staging]

permissions:
  id-token: write     # <--- REQUIRED for OIDC to work
  contents: read

jobs:
  deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: "v1.32.3"
        id: install

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.STAGING_GITHUB_ACTION_DEPLOY_ROLE }}
          aws-region: ap-southeast-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push image server main to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: yoyo-store-server-main
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build \
            -f server_main/Dockerfile.deploy \
            --build-arg ENVIRONMENT=staging \
            -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Build, tag, and push image server invoice to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: yoyo-store-server-invoice
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build \
            -f server_invoice/Dockerfile.deploy \
            --build-arg ENVIRONMENT=staging \
            -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Build, tag, and push image frontend to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: yoyo-store-frontend
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build \
            -f frontend/Dockerfile.deploy \
            --build-arg ENVIRONMENT=staging \
            -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Update kube config
        run: aws eks --region ap-southeast-1 update-kubeconfig --name eks-yoyo-store

      - name: Debug - check nodes
        run: kubectl get nodes

      - name: Deploy all manifests with envsubst
        env:
          ENVIRONMENT: staging
          CONTAINER_IMAGE_YOYO_MAIN: ${{ steps.login-ecr.outputs.registry }}/yoyo-store-server-main:${{ github.sha }}
          CONTAINER_IMAGE_YOYO_INVOICE: ${{ steps.login-ecr.outputs.registry }}/yoyo-store-server-invoice:${{ github.sha }}
          CONTAINER_IMAGE_YOYO_FRONTEND: ${{ steps.login-ecr.outputs.registry }}/yoyo-store-frontend:${{ github.sha }}
        run: |
          for f in deployment-manifest/*.yaml; do
            envsubst < "$f" | kubectl apply -f -
          done